### PR TITLE
Add no-concat switch

### PR DESCRIPTION
**Pull request by berni44**
Might this be a solution to issue #61?

### CODE REVIEW

**Comment by CyberShadow** [comment]
Instead of having a switch specific to one reduction type, I think it would be better to just prevent code marked as not to be removed from being moved, i.e. participating in any kind of reductions.

**Comment by berni44** [comment]
My reasoning was, that people might generally be interested in keeping stuff inside the file it has originally been (if it cannot be removed for whatever reason). At least, I was quite surprised when I learned that stuff can move between files. In this regard, `concat` is somewhat special...

**Comment by CyberShadow** [comment]
> My reasoning was, that people might generally be interested in keeping stuff inside the file it has originally been (if it cannot be removed for whatever reason).

This doesn't really align with the typical use case for DustMite. In any case, you can trivially test for this in your test script.

> At least, I was quite surprised when I learned that stuff can move between files. In this regard, `concat` is somewhat special...

Future versions of DustMite might have other reduction types which move code around, such as attempts to inline functions.

**Comment by berni44** [comment]
I realize, that you've got a slightly different vision on what dustmite is doing. So I'm closing this, as I can always use it for my own purpose. Never mind.

**Pull request closed without merging**
